### ISSUE TITLE
hardened runtime?

### ISSUE THREAD

**Issue by tofutim** [achow101/signapple#3]
Is it possible to use this to sign with hardened runtime? (--options=runtime)

**Comment by achow101** [comment]
I do not normally work on Mac applications, so I do not know, but I would guess that this cannot do that. From the [docs](https://developer.apple.com/documentation/security/hardened_runtime), it seems that hardened runtime is something set in an entitlement, and currently this project cannot set entitlements. However the code for signing entitlements is there, just not any way to set entitlements.

**Comment by tofutim** [comment]
Thanks for the response. I am investigating how to notarize a mac app, and it seems that one has to use Apple's codesign to set --options=runtime. But maybe there is a way to do it with signapple so that my `detached-sig-create.sh` doesn't have to switch from signapple to codesign.

**Comment by achow101** [comment]
I've added an option that enables hardened runtime when signing.
